#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom data.table .SD
#' @importFrom data.table :=
#' @importFrom data.table as.data.table
#' @importFrom data.table copy
#' @importFrom data.table data.table
#' @importFrom data.table dcast
#' @importFrom data.table fread
#' @importFrom data.table frollapply
#' @importFrom data.table frollmean
#' @importFrom data.table is.data.table
#' @importFrom data.table rbindlist
#' @importFrom data.table setDT
#' @importFrom data.table setkey
#' @importFrom data.table setnames
#' @importFrom data.table setorder
#' @importFrom data.table shift
#' @importFrom graphics abline
#' @importFrom graphics barplot
#' @importFrom graphics grid
#' @importFrom graphics hist
#' @importFrom graphics legend
#' @importFrom graphics lines
#' @importFrom graphics par
#' @importFrom graphics plot
#' @importFrom graphics text
#' @importFrom stats acf
#' @importFrom stats approx
#' @importFrom stats as.dist
#' @importFrom stats as.formula
#' @importFrom stats cor
#' @importFrom stats cov
#' @importFrom stats cov2cor
#' @importFrom stats dist
#' @importFrom stats hclust
#' @importFrom stats IQR
#' @importFrom stats median
#' @importFrom stats na.omit
#' @importFrom stats qqline
#' @importFrom stats qqnorm
#' @importFrom stats quantile
#' @importFrom stats sd
#' @importFrom stats setNames
#' @importFrom stats var
#' @importFrom TTR CCI
#' @importFrom TTR RSI
#' @importFrom utils head
#' @importFrom utils tail
#' @importFrom utils write.csv
#' @importFrom zoo index
## usethis namespace: end
NULL
